### ISSUE TITLE
Publish to Bower

### ISSUE THREAD

**Issue by gerich-home** [gerich-home/it-depends#10]

**Comment by gerich-home** [comment]
In perfect world bower artifacts need to be published to a separate repo

**Comment by VanDalkvist** [comment]
Why should it be in separate repo?

**Comment by gerich-home** [comment]
Perfect world is possible!
See: http://blog.kevinlamping.com/publishing-bower-components/
and https://www.npmjs.com/package/gulp-gh-pages

We need to create a separate repo and push bower artifacts there!

**Comment by VanDalkvist** [comment]
Awesome! I would like to help you with publishing to bower if you do not mind. Can you create a new repository for it?

**Comment by gerich-home** [comment]
Sure. Wait for a while..
But postpone publishing of current code to bower if possible. I wanna to make next release in a single moment to all places (npm, github, bower, (?)nuget)

**Comment by VanDalkvist** [comment]
Yep, I understand. But you cannot publish it in one moment without preparing :) I was not going to publish it. Just interesting to configure all stuff for it

**Comment by gerich-home** [comment]
Please use this repo: https://github.com/it-depends-js/it-depends-bower
You was invited to the team there, accept it and start playing with it!

**Comment by VanDalkvist** [comment]
Thanks :+1:

**Comment by VanDalkvist** [comment]
I found `$env:access_token` as access token on AppVeyor. Can I use it for pushing new version to bower repository?

**Comment by gerich-home** [comment]
What does it mean? :) I cannot understand the problem you are solving

**Comment by VanDalkvist** [comment]
gulp-gh-pages plugin is pushing new version to git repository. You cannot push any changes without authorisation to github. So, one of ways to push changes use URL like `user:accessToken@github.com/user/your-repo.git`. So, that is why I was talking about github access token

**Comment by gerich-home** [comment]
Well, there are 2 ways for you to test, I think:
1. I make you a contributor here, in this repo. You test your changes in a branch, build on AppVeyor. When ready you just hit a PR from your branch to master.
2. You authorize in AppVeyor, add it-depends project from a list of your repos (https://www.appveyor.com/docs#step-2-add-your-project), start a new build and play around, test. When ready you hit a PR to this repo from your repo and we will test the same in AppVeyor as soon as it gets merged.

I prefer the 2nd as we will test how it is easy to run AppVeyor for a separate repo for the library.

**Comment by VanDalkvist** [comment]
Ok, will try to prepare new AppVeyor build.

**Comment by VanDalkvist** [comment]
Here is my build logs for sure - https://ci.appveyor.com/project/VanDalkvist/it-depends/build/1.0.42 . I turned off tests because of coverage and fast testing.

**Comment by VanDalkvist** [comment]
Maybe it will be right to turn off `issues` and `pull-requests` for [it-depends-bower](https://github.com/it-depends-js/it-depends-bower) repository.

**Comment by gerich-home** [comment]
`issues` - done.
`pull-requests` - don't know how..

**Comment by VanDalkvist** [comment]
https://github.com/dear-github/dear-github/issues/84 - they do not have this feature yet...

**Comment by gerich-home** [comment]
Implemented in#53
