### ISSUE TITLE
Move `coveralls` gulp task to appveyor.yml?

### ISSUE THREAD

**Issue by VanDalkvist** [gerich-home/it-depends#55]
During creating new Appveyor build I faced out with issue - I could not pass a build with `unit-tests` gulp task because it depends on `coveralls` task which should be configured for appveyor build previously. I am proposing move `coveralls` task somewhere to be executed after unit-tests are done.

**Comment by gerich-home** [comment]
Agree, this needs to be changed.
We could:
1. Move the logic of https://github.com/gerich-home/it-depends/blob/master/gulp/unit-tests.js#L26 to appveyor.yml for now
2. Add one more check to https://github.com/gerich-home/it-depends/blob/master/gulp/unit-tests.js#L26 to verify we have decrypted coveralls.yml file in the repo root.

As a bigger task we could move to gulp 4 and use the approach proposed in the end of this article: http://blog.reactandbethankful.com/posts/2015/04/23/building-with-gulp-3-and-4-part-1-examples/

**Comment by VanDalkvist** [comment]
About gulp 4. It is not released yet, as I see. https://github.com/gulpjs/gulp/releases

**Comment by gerich-home** [comment]
ah, ok. Well - then just 1 or 2. Or both at once.

**Comment by VanDalkvist** [comment]
I can do it I think

**Comment by gerich-home** [comment]
Do it! :)

**Comment by VanDalkvist** [comment]
Closed due to #62
